twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form/form.html.twig']
    globals:
        ga_tag: '%env(resolve:GTAG)%'
    exception_controller: null
