#controllers:
#    resource: ../../src/Action/
#    type: annotation

controllers:
    resource: ../../src/UI/Action/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
