# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    paramsMailApp:
        name: 'Jérôme Sauvage'
        email: 'test@test.com'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $webRootDir: '%kernel.project_dir%/public'
            $dsn: '%env(resolve:MAILER_DSN)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Model,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\UI\Action\:
        resource: '../src/UI/Action'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\UI\Handler\ContactHandler:
        arguments:
            $eventDispatcher: '@event_dispatcher'

    App\UI\Service\MailerService:
        arguments:
            $mailer: '@mailer.mailer'
            $paramsMailApp: '%paramsMailApp%'

    App\UI\Service\FlashService:
        autowire: true

#        tags:
#            - { name: 'kernel.event_listener', event: 'app.flash_message' }
#            - { name: 'kernel.event_subscriber' }
#            - { name: 'kernel.event_listener', event: 'kernel.response', method: 'onKernelResponse' }

#    App\UI\Service\FlashService:
#        tags:
#            - { name: 'kernel.event_listener', event: App\UI\Event\ContactMailEvent, method: 'onContactMail' }
#
